### ISSUE TITLE
Graph "scrubbing" is too agressive

### ISSUE THREAD

**Issue by BigBlueHat** [mcollina/levelgraph-jsonld#45] opened 2017-01-13 16:53 UTC
I'm working on a test for this (and understanding more about what changed), but here's the set of steps for playing with on [the playground](https://bigbluehat.github.io/levelgraph-playground/).

1. empty graph
2. put
```json
{"@context": "https://schema.org/", "@id": "http://bigbluehat.com/#", "name": "BigBlueHat"}
```
3. `expect(triples).to.have.length(1)` is true
4. put
```json
{"@context": "https://schema.org/", "name": "BigBlueHat"}
```
5. `expect(triples).to.have.length(2)` is false...there's only one. It replaced (maybe?) the original statement that had the ID. 😕 
6. put the JSON-LD from # 2 (above)
7. `expect(triples).to.have.length(2)` is true...um...OK...
8. put the JSON-LD from # 4 (above)...trying again
9. `expect(triples).to.have.length(3)` is true...gah! WAT?! I'm back down to 1 😢 

Obviously...I'm missing something important here... 😀 

@jmatsushita thoughts?

**Comment by jmatsushita** [comment] 2017-01-13 17:08
The original `put` is quite aggressive which is why I've started contributing here and added a `preserve` option, you might want to use it by default [when you open the db](https://github.com/mcollina/levelgraph-jsonld#usage). I'm not exactly sure about what happens with step 4 though. It's likely it will be addressed by `preserve: true` but it's still a bit mysterious.

**Comment by BigBlueHat** [comment] 2017-01-13 17:15
Yeah. I'm adding it as an option to the playground per `put()`.

However, it's currently `false` in the playground. Which means I've also found this bit of mystery (which you can try in the console on [the playground](https://bigbluehat.github.io/levelgraph-playground/)):
1. Load some stuff into the graph (aka. click the "put" button).
2. Run this in the console:
```js
db.jsonld.put('{"@context": "https://schema.org/", "name": "BigBlueHat"}', console.log.bind(console));
```
3. Say goodbye the entirety of the graph...except that statement...

Regardless of the above (which I assume are bugs), I think setting `preserve` to `true` by default is prudent. I'd much rather have messy data than no data. 😄

**Comment by jmatsushita** [comment] 2017-01-13 17:17
Yes I think having preserve to true by default makes sense too. @mcollina Should we go all the way here?

**Comment by jmatsushita** [comment] 2017-01-13 17:20
@BigBlueHat you might be interested in #46 as well

**Comment by jmatsushita** [comment] 2017-01-13 17:41
Ok I've been able to reproduce the problem @BigBlueHat and since I can build the playground now I'll work on a fix.

**Comment by jmatsushita** [comment] 2017-01-13 18:01
Well turns out there were several things at play here:
 - `preserve` did need to be `true`.
 - `base` shouldn't be put to `_:` which basically means everything is a blank node (and blank node really aren't event supposed to be persisted, or let's say it's not trivial how they should be)
 - there's a bug with setting "@context" as a string. #47

So if you do correct the options and use a "@context" object then things work as expected. I'll get to the fix now.

**Comment by BigBlueHat** [comment] 2017-01-13 18:14
[New Playground with options settings is up!](https://bigbluehat.github.io/levelgraph-playground/)

Consequently, you'll find some more interesting things...

Basically, there's all kinds of crazy variations depending on where `@base` shows up, what `@id` is set to, or if any of its missing.

Right now, the playground is passing in `{base: "", preserve: true}` by default, fwiw.

Oh, and `db` and `app` can be access from the console. `app.displayTriples({})` is your friend there. 😄

**Closed** 2017-01-14 13:37 UTC
